pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
                //echo "build"
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
                //echo "test"
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                    //echo "post"
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                //echo "Deliver"
            }
        }
        stage('Complete') {
            steps {
                echo 'Job Complete!'
            }
        }
    }
}
